apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-api-config
  namespace: assessment
data:
  APP_VERSION: "2.0.0"
  STARTUP_DELAY_MS: "20000"
  UPSTREAM_API_TOKEN: "assessment-placeholder-token"
