apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-api
  namespace: assessment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-api
  template:
    metadata:
      labels:
        app: customer-api
    spec:
      containers:
        - name: customer-api
          image: customer-api:assessment
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: customer-api-config
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 10  
            periodSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
            failureThreshold: 3
